os:
- linux
- macos
dist: xenial
language:
- python
- cpp
compiler:
- gcc
- clang
python:
- "3.7"
addons:
  apt:
    packages:
      - cmake
script:
- python setup.py test
branches:
  only:
  - master
