language:
- python
- cpp
python:
- 3.7
compiler:
  - gcc
  - clang
os:
- linux
- macos
dist: xenial
addons:
  apt:
    packages:
      - cmake
script:
- python setup.py test
branches:
  only:
  - master